#!/usr/bin/env python
# lunch config file for the custom project postures/NTA
# Copy this to ~/.lunch/config
# 
# All you need to do here is to call add_command() for each command you want to add 
# to the distributed process launcher. 
# lunch is a distributed process launcher for GNU/Linux. see postures/trunk/py/
# -------------------------------------------------------------------
# some variables

_host = "posture01"

_user = "postures" # Remote user for example tests.
_src = "/home/%s/src" % (_user)

# camera -> receiver relationships:
_milhouses = [ {"sender":_host, "camera":0, "receiver":_host },
               {"sender":_host, "camera":1, "receiver":_host } ]

_milhouses = []

# more variables for the paths
_nta = "%s/nta" % (_src)
_postures = "%s/postures/trunk" % (_src)
_spinwidgets = "%s/spinwidgets" % (_src)
_spin = "%s/spinframework/trunk" % (_src)
_nta_client = "%s/pd-0.41-4/bin/pd -jack %s/ntaClient.pd" % (_src, _nta)
_pano_viewer = "%s/postures/trunk/panoViewer/panoViewer" % (_src)
_spinEditor = "%s/pd-0.41-4/bin/pd -jack %s/patches/spinEdit.pd %s/milhouseTest.pd" % (_src, _spinwidgets, _nta)


# -------------------------------------------------------------------
# local:

# le serveur (local):
add_command("spinServer", title="spinServer (local)", sleep=1.0, priority=1) 

# viewer
add_command("spinViewer", env={"DISPLAY":":0.0"}, user=_user, host=_host, title="spinViewer")

# ntaClient:
add_command(_nta_client, env={"DISPLAY":":0.0"}, user=_user, host=_host, title="ntaClient")

# remove all shared memory:
add_command("rm /dev/shm/posture*", user=_user, host=_host )

# milhouse invocations:
for m in _milhouses:
    add_command("firereset", user=_user, host=m['sender'], title="firereset")
    add_command("milhouse -s --videoport %s --address %s --videocodec h263 --videosource dc1394src --videobitrate 750000 --camera-number %d" % (10000 + (20*m['camera']), m['receiver'], m['camera']), user=_user, host=m['sender'], title="milhouse_sender_%s_%d" % (m['sender'], m['camera']))
    add_command("milhouse -r --videoport %d --videocodec h263 --address %s --videosink sharedvideosink --shared-video-id %s_%d" % (10000+(20*m['camera']), m['sender'], m['sender'], m['camera']), user=_user, host=m['receiver'], title="milhouse_receiver_%s_%d" % (m['sender'],m['camera']))

# local editor:
add_command(_spinEditor, env={"DISPLAY":":0.0"}, title="spinEditor (local)")
