#!/usr/bin/env python
# lunch config file for the custom project postures/NTA
# Copy this to ~/.lunch/config
# 
# All you need to do here is to call add_command() for each command you want to add 
# to the distributed process launcher. 
# lunch is a distributed process launcher for GNU/Linux. see postures/trunk/py/
# -------------------------------------------------------------------

import os
execfile(os.path.join(os.path.dirname(__file__), "postures.py"))

add_command("spinServer", title="spinServer (local)", sleep=1.0, priority=1) 
add_command(postures.ntaClient, env={"DISPLAY":":0.0"}, user=postures.user, host="posture01", title="ntaClient")
add_command("panoViewer", env={"DISPLAY":":0.0"}, user=postures.user, host="posture01", title="panoViewer")
add_command(postures.spinEditor, env={"DISPLAY":":0.0"}, title="spinEditor (local)")
