#!/usr/bin/env python
# lunch config file for the custom project postures/NTA
# Copy this to ~/.lunch/config
# 
# All you need to do here is to call add_command() for each command you want to add 
# to the distributed process launcher. 
# lunch is a distributed process launcher for GNU/Linux. see postures/trunk/py/
# -------------------------------------------------------------------

# some variables
_user = "postures"
_src = "/home/%s/src" % (_user)
_nta = "%s/nta" % (_src)
_postures = "%s/postures/trunk" % (_src)
_spinwidgets = "%s/spinwidgets" % (_src)
_spin = "%s/spinframework/trunk" % (_src)
_pdClient = "%s/pd-0.41-4/bin/pd -jack %s/patches/spinEdit.pd %s/ntaClient.pd" % (_src, _spinwidgets, _nta)

# -------------------------------------------------------------------

add_command("spinServer", title="local_spinServer", sleep=1.0, priority=1) 

#add_command("spinViewer", title="local_spinViewer")
add_command("panoViewer", title="panoViewer")

add_command(_pdClient, title="local_Pd")

