#!/usr/bin/env python
# lunch example config file.
# Copy this to ~/.lunchrc
#
# In this example, we run a command on a remote host, via SSH.

HOST = "brrr"
USER = "miville"

# local:
add_command("xlogo", title="local_xlogo")
add_command("xeyes", title="local_xeyes")
# remote: (on remote host's display)
add_command("xeyes", env={"DISPLAY":":0.0"}, user=USER, host=HOST, title="remote_xeyes")
