#!/usr/bin/env python
# lunch example config file.
# Copy this to ~/.lunchrc
# 
# All you need to do here is to call add_command() for each command you want to add 
# to the distributed process launcher. 
#
# The following variables are only there to simplify test.
#
_host = "brrr" # Remote host for example tests.

# local:
add_command("xlogo", title="local_xlogo")
add_command("xeyes", title="local_xeyes")

# remote: (on remote host's display)
add_command("xlogo", env={"DISPLAY":":0.0"}, host=_host, title="remote_xlogo")
